[WIP] Introduce font-color and font-background-color plugins
ckeditor/ckeditor5-font pull request #25
Opened 2019-03-20 16:12 UTC by msamsel

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))
https://github.com/ckeditor/ckeditor5/issues/1457
Feature: Add Font Color and Font Background Color plugins. Closes ckeditor/ckeditor5#1457.

---

### Additional information

* Together with this change is required to change branch in `core` and `highlight`. I re-use rubber icon, which was moved to core from highlight.

2019-03-20 16:15 UTC, mlewand reviewed
Couple of early review notes:

- [x] Remove color button does not use "pointer" cursor upon hover
- [x] I don't think you're supposed to be able to click into inactive icon (it shows the outline, despite not doing anything). I believe it's an upstream, is it already tracked somewhere @msamsel?
- [x] The default color palette must come with (localized) labels.
- [ ] Manual test should include some description.

2019-03-21 08:54 UTC, msamsel commented
> I don't think you're supposed to be able to click into inactive icon (it shows the outline, despite not doing anything). I believe it's an upstream, is it already tracked somewhere @msamsel?

I've report it here as I couldn't find similar issue: https://github.com/ckeditor/ckeditor5-ui/issues/473.

2019-03-21 10:04 UTC, oleq requested changes
The feature looks promising 🎉 but there are some things that needs fixing.

P.S. I didn't point it out inline but almost every prop, method, class and config are missing docs.

We need a feature guide in https://ckeditor.com/docs/ckeditor5/latest/features/index.html too.

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorcommand.js
> +import { FONT_BACKGROUND_COLOR } from '../utils';
Code style: missing new line.

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorediting.js
> +
Code style: too many new lines :p

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorediting.js
> + * @module font/fontfamily/fontfamilyediting
Docs: Wrong path.

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +export default class FontBackgroundColorUI extends Plugin {
Code style: missing new line.

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +			const colorTableView = colorUI.addColorsToDropdown(
Why do we need this `ColorUI namespace`? It holds just a single function? Why not a plain helper instead?

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +				options.map( element => ( {
Destructuring?

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +				if ( val.value !== null ) {
`val.value` looks weird. There's something wrong with the naming convention somewhere if it comes to that.

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +					colorTableView.recentlyUsedColors.add( { color: val.value, hasBorder: val.hasBorder, label: val.label }, 0 );
Let's put the props in separate lines. It's hard to read.

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +		return colors;
`return normalizeOptions(...`

2019-03-21 10:04 UTC, oleq commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +	 * Returns options as defined in `config.fontFamily.options` but processed to account for
This entire doc string should be about font bg color, not font family.

2019-03-21 10:04 UTC, oleq commented on src/fontcolor/fontcolorcommand.js
> +export default class FontColorCommand extends FontCommand {
Missing new line.

2019-03-21 10:04 UTC, oleq commented on src/fontcolor/fontcolorediting.js
> + * @module font/fontfamily/fontfamilyediting
Wrong path.

2019-03-21 10:04 UTC, oleq commented on src/fontcolor/fontcolorediting.js
> +
Too many new lines.

2019-03-21 10:04 UTC, oleq commented on src/fontcolor/fontcolorediting.js
> +		editor.model.schema.extend( '$text', { allowAttributes: FONT_COLOR } );
Out of curiosity: why it is that this line must be in `init()` and not in the constructor? Does it have something to do with other editor plugins?

2019-03-21 10:04 UTC, oleq commented on src/fontcolor/fontcolorui.js
> +/**
TBH this entire files is just a copy of `fontbackgroundcolorui.js`, right? Maybe let's have them both use the same UI component then? DRY.

2019-03-21 10:04 UTC, oleq commented on src/ui/colorgrid.js
> +
No `@module` docs.

2019-03-21 10:04 UTC, oleq commented on src/ui/colorgrid.js
> +				this.fire( 'execute', { value: item.color, hasBorder: item.options.hasBorder, label: item.label } );
Please avoid object long single–line obj literals.

2019-03-21 10:04 UTC, oleq commented on src/ui/colortableview.js
> +
No `@module` docs.

2019-03-21 10:04 UTC, oleq commented on src/ui/colortableview.js
> +import removeButtonIcon from '@ckeditor/ckeditor5-core/theme/icons/eraser.svg';
Generally we import js first, then svg and css.

2019-03-21 10:04 UTC, oleq commented on src/ui/colortableview.js
> +		this.set( 'removeButtonTooltip' );
Why is this prop observable? Does it change at some point?

2019-03-21 10:04 UTC, oleq commented on src/ui/colortableview.js
> +		this.set( 'hoveredColor' );
I don't see this prop used anywhere.

2019-03-21 10:04 UTC, oleq commented on src/ui/colortableview.js
> +		this.set( 'colorColumns', 5 );
Why is this prop observable? It's a constant isn't it?

2019-03-21 10:04 UTC, oleq commented on src/ui/colortableview.js
> +		this.set( 'recentlyUsedColors', new Collection() );
Why is this prop observable? Is the collection re–initialised from scratch at some point?

2019-03-21 10:04 UTC, oleq commented on src/ui/colortableview.js
> +					colorTile.set( 'isEnabled', false );
`colorTile.set( 'isEnabled', colorObj.isEnabled );` ?

2019-03-21 10:04 UTC, oleq commented on src/ui/colortile.js
> +import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';
Missing new line.

2019-03-21 10:04 UTC, oleq commented on src/utils.js
> +function getColorsDefinition( color ) {
`getColorDefinition` if anything. But this has something to do with the conversion — maybe there's a better name for it?

2019-03-21 10:04 UTC, oleq commented on src/utils.js
> +export const colorUI = {
As I wrote earlier, this namespace is pointless with a single function like this.

2019-03-21 10:23 UTC, oleq requested changes
Some changes in styles are required too.

2019-03-21 10:23 UTC, oleq commented on theme/fontcolor.css
> +	--ck-table-color-padding: 10px;
Please use constants from `_spacing.css` instead.

2019-03-21 10:23 UTC, oleq commented on theme/fontcolor.css
> +	cursor: pointer;
This is a wrong cursor. A default one should be used instead. Pointer is reserved for links.

2019-03-21 10:23 UTC, oleq commented on theme/fontcolor.css
> +	border-radius: var(--ck-border-radius);
Use `@mixin ck-rounded-corners` instead.

2019-03-21 10:23 UTC, oleq commented on theme/fontcolor.css
> +.ck .ck-button.ck-button_with-text.ck-color-table__remove-color svg {
What is wrong with default `.ck-button` styles? They are shared across the project.

2019-03-21 10:23 UTC, oleq commented on theme/fontcolor.css
> +	cursor: pointer;
This is wrong and does not even work BTW :P

2019-03-21 10:24 UTC, oleq commented
Also

```
(master 863a704) oleq@MBP15 ~/ck/5/ckeditor5> yarn docs --skip-snippets
yarn run v1.13.0
$ node ./scripts/docs/build-docs.js --skip-snippets
JSDoc started...
Memberof property should start with 'module:'. Got 'ColorTableView' instead.
	at /Users/oleq/ck/5/ckeditor5/packages/ckeditor5-font/src/ui/colortableview.js (line 137)


Validation Summary:
 * Validator found 1 errors.
Documented 421 files!
Clean build directory.
Emptying Hexo source directory.
Building API docs of CKEditor 5...
Built API docs in: 9614.659ms
Error: Invalid internal links in /ckeditor5/12.0.0/api/module_font_fontbackgroundcolor_fontbackgroundcolorcommand.html:
  * 'module_font_fontbackgroundcolor_fontbackgroundcolorcommand.html#FontBackgroundColorCommand' - FontBackgroundColorCommand
Error: Invalid internal links in /ckeditor5/12.0.0/api/module_font_fontcolor_fontcolorcommand.html:
  * 'module_font_fontcolor_fontcolorcommand.html#FontColorCommand' - FontColorCommand
Error: Invalid internal links in /ckeditor5/12.0.0/api/module_font_fontfamily_fontfamilyediting.html:
  * 'module_font_fontfamily_fontfamilyediting.html#FontBackgroundColorEditing' - FontBackgroundColorEditing
  * 'module_font_fontfamily_fontfamilyediting.html#FontColorEditing' - FontColorEditing
Running webpack for app.js ...
```

2019-03-21 10:25 UTC, oleq commented on theme/fontcolor.css
> +.ck .ck-button.ck-button_with-text.ck-color-table__remove-color svg {
If it looks like they need fixing, this should be done somewhere in `button.css` instead, so the entire project benefits from the fix. Do we use this kind of button anywhere anyway?

2019-03-21 10:27 UTC, oleq commented on theme/fontcolor.css
> +.ck .ck-button.ck-button_with-text.ck-color-table__remove-color svg {
Check out [theme lark MT](http://localhost:8125/ckeditor5-theme-lark/tests/manual/theme.html). It should look good without any additional tuning

![image](https://user-images.githubusercontent.com/1099479/54746346-353b4880-4bcc-11e9-902d-43d2bf9b5252.png)

cc @dkonopka

2019-03-21 11:32 UTC, msamsel commented on src/fontcolor/fontcolorediting.js
> +		editor.model.schema.extend( '$text', { allowAttributes: FONT_COLOR } );
Not really. I just take inspiration from other plugin.

2019-03-21 13:04 UTC, msamsel commented on src/fontbackgroundcolor/fontbackgroundcolorui.js
> +				options.map( element => ( {
I'm not sure what you have on your mind here. There is returned array with objects, where I only take few of object's properties. Can you give me more hints what you had on your mind?

2019-03-22 11:33 UTC, msamsel commented on src/ui/colortableview.js
> +					colorTile.set( 'isEnabled', false );
It have to be resist for case when `colorObj.isEnabled` is undefined. However if you think that that better is to compress it, I could make sure that `colorObj.isEnabled` will be alway set up to true or false.

2019-03-28 17:53 UTC, jodator commented
WiP (I'll update this comment later on):

- consider different keyboard navigation #26 
- currently selected color is not focused no keyboard:

![Peek 2019-03-28 18-53](https://user-images.githubusercontent.com/247363/55180865-bf664c80-518a-11e9-8e1d-189155ea3469.gif)

2019-03-29 10:33 UTC, jodator commented
OK. I think I'm done with reading all that :D

2019-03-29 13:41 UTC, mlewand commented
## Corrections

> The default value registers 15 colors:

changed to:

> The default value registers following colors:

It's better not to mention too much details of value that is right below, that way we reduce thw chance that someone edits the listing alone (adds/removes some colors) without updating this particular line.

I have simplified manual test description (it was basically duplicating the editable contnet).

## Issues

* The "recent/document" colors feature to pick up pasted/preloaded colors is missing, but this should not be blocking this PR extracted to #28.
* `hasBorder` property won't work properly, as here the assumption is that the skin will be bright (as it's applied to bright colors). It won't work without reconfiguration with dark themes.

minor:

* There's no string value example in `FontBackgroundColorConfig.colors` (and respective font color struct).
* FontBackgroundColorConfig and FontColorConfig implement identical interface and both have the same default values. It would improve DRY factor to have a common interface for both features. I see that now the listings differ in both, but having common interface should simply mention both configuration names.


Above things will be extracted to a separate issues not to block this PR.

Ok all the things extracted, PR is ready to land on master branch. I'll merge it in few mins.

2019-03-29 13:42 UTC, mlewand approved these changes
Ok all the things extracted, PR is ready to land on master branch. I'll merge it in few mins.

2019-03-29 14:13 UTC, merged