Update priorities in font plugin
ckeditor/ckeditor5-font pull request #44
Opened 2019-05-13 15:09 UTC by msamsel

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Update priorities in font plugin. Closes #35.

---

### Additional information

* Priorities are set up to 7, to be higher than link (5), but lower than basic-styles (10). To have result that link remain most outer element and basic-styles elements will be always inside font features.

2019-05-30 13:35 UTC, jodator requested changes
The changes are OK I don't like the previous code for tests ;)

Small update but be better for the future when looking back on those tests.

2019-05-30 13:35 UTC, jodator commented on tests/utils.js
> +		it( 'addColorTableToDropdown()', () => {
I've just noticed it. The test are wrongly named... the `it()` part doesn't say much what the test does. It'd be nicer to structure the tests as:

```js
describe( 'utils', () => {
	describe( 'normalizeColorOptions()', () => {
		it( 'should return normalized config object' );
	} );
} );
```

or even

```js
describe( 'utils', () => {
	describe( 'normalizeColorOptions()', () => {
		it( 'should return normalized config object (string)' );

		it( 'should return normalized config object (object with name)' );

		it( 'should return normalized config object (object with name)' );
	} );
} );
```

The tests (as they test the same) might be put to util funciton and used to create thos test:

```js
testConfig( 'should return normalized config object (object)', { color: 'black' }, { /* output to assert */ } )
```

right now the tests doesn't say much what they test.

2019-05-30 13:44 UTC, jodator commented
@msamsel also could you check if you can do anything about those tests on edge? I hate that it renders attributes/styles in different order.

If there's and issue with writing one test for all browsers we probably sould create and issue for that (I also [had that issues](https://github.com/ckeditor/ckeditor5-mention/pull/76/commits/8f1c4c58b397d5a9ef5d0b37704cbe85f11ff60d)).

If you'd go with `env.isEdge` in tests to alter those checks then we're going to create an issue for this.

2019-05-30 15:01 UTC, msamsel commented
> @msamsel also could you check if you can do anything about those tests on edge? I hate that it renders attributes/styles in different order.

I couldn't find nice solution for that, and I want to combine all 4 fonts' features to check if all are merged into single span. So `env.isEdge` seems to be only reasonable solution.

Alternatively I could use `match()`, however using complicated regular expression might significantly decrease readability in that test.

Should I create an issue for those sorting attributes problem?

2019-05-30 15:05 UTC, jodator commented
> Should I create an issue for those sorting attributes problem?

Sure - it happens to me also so we should track it :)

2019-05-31 07:31 UTC, jodator commented
@msamsel could you also do the `desribe() > it()` for other tests from that file? One `it()` fill be fine for each `it( 'someMethod()' )` which is still there.

2019-05-31 10:00 UTC, jodator approved these changes
LGTM :+1:

2019-06-26 08:51 UTC, merged