T/4: Initial Font plugin implementation.
ckeditor/ckeditor5-font pull request #5
Opened 2018-01-10 13:20 UTC by jodator

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Initial Font feature implementation. Closes #2. Closes #3. Closes #4.

---

### Additional information

* This came with minor changes in UI/Theme required to have button in toolbar nicely rendered. I've pushed:
    - https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-font/4 (updated mgit.json for PR review).
    - https://github.com/ckeditor/ckeditor5-ui/tree/t/ckeditor5-font/4.
    - https://github.com/ckeditor/ckeditor5-theme-lark/tree/t/ckeditor5-font/4.

The changes in UI/Theme changes which element gets borders and white background by default. Now it's only to dropdown button with label only - other types of buttons are rendered as buttons.

I have only *one* major issue with this PR which requires talks/decisions. I've used Regex to create `view` converter definition for Font Family as `font-family` inline styles [might be defined](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) in various ways in HTML - by using quotes (single/double) or by not using them. So there's a regex that checks any variation of:
- Long Font Name, Other Font Name
- "Long Font Name", Other Font Name
- Long Font Name, 'Other Font Name'
- ... etc

https://github.com/ckeditor/ckeditor5-font/blob/c77be7eb2d85820b9515bef63d15b8eae21f3f92/src/fontfamily/utils.js#L58-L98

What I can create instead is a use of a callback that would basically to what this regex but programatically. Only thing would be updating documentation in `definition-based-coverters` (and `ViewElementDefinition`, etc) to reflect this behavior.

2018-01-10 13:22 UTC, jodator commented
I've asked @oleq for review - mostly of UI/Theme part changes as they might come in line with proposed changes to [dropdowns family](https://github.com/ckeditor/ckeditor5-ui/issues/356).

2018-01-12 11:59 UTC, jodator commented
I've  created proper PR in https://github.com/ckeditor/ckeditor5-theme-lark/pull/121.

2018-01-12 15:06 UTC, Reinmar commented
* Current font family is not marked in the dropdown's panel. 
* You cannot apply font family to a collapsed selection and start typing.

The same issue occur in font size.

2018-01-16 08:17 UTC, jodator commented
I"ve removed the `t/ckeditor5-font/4` branch in `ckeditor5` as it is superfluous after merging `theme-lark` PR. Those 2 issues will be fixed shortly after this.

2018-01-16 10:27 UTC, jodator commented
Issues from initial review fixed.

ps.: I'd like to know more about your thoughts on that RegExp issue I've posted initially ;)

2018-01-16 10:49 UTC, Reinmar commented
Try this TC:

1. Select all content with ctrl+a
2. Choose either the default font size or default font family

Neither will work.

2018-01-16 10:50 UTC, Reinmar commented
Actually, it's not about the default style, but any style. None of the styles will work if (I guess) image is selected.

This is a quite important use case now because there's no "clear formatting" button.

2018-01-16 13:09 UTC, Reinmar commented
As for the regexp – I've got mixed feelings. I think that we don't have to care about manually crafted font names. We only need to care about correctly loading data created with the editor. There's much more than quotes than can go wrong here and it's not yet time to worry about these situations. Some examples:

* `font` was used instead of `font-family`,
* some characters were encoded in `font-family`'s value,
* there's only a partial match for a font family name – e.g. only the first name was used.

All these cases may happen with a pasted content and a complete solution for them would be extremely complex. We've seen that in CKEditor 4 already where a bit too aggressive normalisation was actually breaking stuff rather than helping.

Therefore, let's:

* remove that whole regexp,
* add tests for `setData( getData() )` cases to see that all browsers accept and maintain our single-quoted font names.

2018-01-16 13:22 UTC, Reinmar commented
One note for me: I was wondering whether the feature's behaviour to get the dropdown item's label from the font-family value is ok. Whether it won't fail in some special cases where a better control is needed on that.

The answer is: a developer can always use the full-flavoured object notation to define the values manually.

2018-01-17 10:53 UTC, jodator commented
> Try this TC:
> 
>     Select all content with ctrl+a
>     Choose either the default font size or default font family
> 
> Neither will work.

This is a selection bug unfortunately. The selection is collapsed when using `ctrl+A` and the last item in content is a widget.

2018-01-22 10:55 UTC, Reinmar commented
We'll also need a documentation like in https://github.com/ckeditor/ckeditor5-alignment/commit/09b92aff9a70329914f4aeea128aeb935b939c17.

2018-01-25 16:23 UTC, oleq commented
BTW, is it by design that size of the font is reflected by the label only?

![image](https://user-images.githubusercontent.com/1099479/35399157-ec685b70-01f3-11e8-9469-0190e8d59d76.png)

IMO even if it will not correspond to the actual size of the text in editable (different CSS tree, possibly different styles), slightly bigger/smaller labels would be great for the overall UX. E.g. it's hard to figure out at first glance if the list is ascending or descending.

2018-01-25 16:27 UTC, jodator commented
> BTW, is it by design that size of the font is reflected by the label only?

I got such impression during some talks that for font-size it should be the same size. (Maybe it was @dkonopka - but I don't really remember). Ps.: you can also can have `px` sizes:

![selection_008](https://user-images.githubusercontent.com/247363/35399634-fcba5450-01f4-11e8-8cdc-580269fed0bc.png)

2018-01-25 16:53 UTC, oleq commented
> Ps.: you can also can have px sizes:

Even with PX sizes, I'd still give users some hint about what they would look like in the content. WDYT @dkonopka?

2018-01-25 17:40 UTC, jodator commented
Aaaand the guides are ready to review. I give my best at them but @Reinmar will probably find something to fix there ;).

ps. I'm waiting for the dropdown UX final solution to eventually fix that.

2018-01-26 15:22 UTC, dkonopka commented
> Even with PX sizes, I'd still give users some hint about what they would look like in the content. > WDYT @dkonopka?

Like in paragraph dropdown (heading 1 & 2 different sizes), I'm for "graphical" for px & named font-sizes. 👍

2018-01-29 16:35 UTC, jodator commented
@oleq & @Reinmar OK I've added the FontSize dropdown behavior as requested for both presets and numeric configuration.

2018-02-01 16:11 UTC, jodator commented
This PR might as well wait for PR with dropdowns: https://github.com/ckeditor/ckeditor5-ui/issues/344 as some work is also done @ https://github.com/ckeditor/ckeditor5-font/tree/t/ckeditor5-ui/344 branch.

2018-02-02 12:46 UTC, jodator commented
I've updated this PR with changes in dropdowns. So this is ready to review after: https://github.com/ckeditor/ckeditor5-ui/pull/361.

2018-02-12 16:09 UTC, oleq requested changes
The code looks great. What we need is a better, more verbose documentation to help developers use the (sub–)features we developed.

2018-02-12 16:09 UTC, oleq commented on docs/features/font-size.md
> +The {@link module:font/fontsize~FontSize} feature enables support for setting font size.
I'm afraid this is not a very rich introduction. We should clearly state here that the feature is about inline elements, classes and the `style` attribute.

2018-02-12 16:09 UTC, oleq commented on docs/features/font-family.md
> +The {@link module:font/fontfamily~FontFamily} feature enables support for setting font family.
See my first comment in the font-size.md.

2018-02-12 16:09 UTC, oleq commented on docs/features/font-size.md
> +Use the special keyword `'normal'` to use the default font size defined in the web page styles.
Why `normal` but not `default`? Font size defined `default` for the same purpose. Is this by design?

2018-02-12 16:09 UTC, oleq commented on src/font.js
> +export default class Font extends Plugin {
This plugin has no manual test and is not even mentioned in docs. What's the purpose of it then?

2018-02-12 16:09 UTC, oleq commented on src/font.js
> + * The Font plugin.
What does it do? Because it requires some classes it does not mean it enables them.

2018-02-12 16:09 UTC, oleq commented on src/fontcommand.js
> +	 *
Extra new line?

2018-02-12 16:09 UTC, oleq commented on src/font.js
> + * The Font plugin.
s/Font/font/

2018-02-12 16:09 UTC, oleq commented on src/fontfamily.js
> + * The Font family plugin.
s/Font/font/

2018-02-12 16:09 UTC, oleq commented on src/fontfamily/fontfamilycommand.js
> + * The font family command. It is used by the {@link module:font/fontfamily/fontfamilyediting~FontFamilyEditing}
Developers will appreciate a simple example like `editor.execute( 'fontFamily', { value: 'tiny' } );`.

2018-02-12 16:09 UTC, oleq commented on src/fontfamily/fontfamilycommand.js
> +	/**
`@inheritDoc`?

2018-02-12 16:09 UTC, oleq commented on src/fontfamily/fontfamilyui.js
> + * @extends module:core/plugin~Plugin
What does it do? What sort of UI does it create? How to use it in the configuration?

2018-02-12 16:09 UTC, oleq commented on src/fontsize/fontsizeediting.js
> + * The Font Size Editing feature.
What does it do? Since we break features into pieces we must explain what each piece is responsible for if developers are expected to use them.

2018-02-12 16:09 UTC, oleq commented on src/fontfamily/fontfamilyediting.js
> + * The Font Family Editing feature.
What does it do? Since we break features into pieces we must explain what each piece is responsible for if developers are expected to use them.

2018-02-12 16:09 UTC, oleq commented on src/fontsize/fontsizeui.js
> + * @extends module:core/plugin~Plugin
Same as font family UI.

2018-02-12 16:09 UTC, oleq commented on docs/features/font-size.md
> +Each size is represented in the view as a `<span>` element with the `text-*` class. For example, the `'tiny'` preset looks as follows in the editor data:
We must clearly state that we don't provide the styles. It's up to developers to style `.ck-content span.tiny {}` and we must show a short snippet how to do that.

2018-02-12 16:15 UTC, oleq commented
I also think that this exponential approach to font previews in docs is a little bit too much 
![image](https://user-images.githubusercontent.com/1099479/36106685-4ceeb660-1018-11e8-8383-63291c67b86c.png)
The last option is just enormous :P

2018-02-12 16:24 UTC, jodator commented
> The last option is just enormous :P

No it's huge ;P

2018-02-12 16:30 UTC, Reinmar commented
Men... always taking about the size.

2018-02-12 16:38 UTC, oleq commented
I was also wondering why these two landed so far from each other in Umberto
![image](https://user-images.githubusercontent.com/1099479/36107789-7884aeda-101b-11e8-83cb-e6990c20954a.png)

2018-02-13 09:19 UTC, Reinmar commented
cc @m-turek

2018-02-13 10:18 UTC, m-turek commented
> I was also wondering why these two landed so far from each other in Umberto

That's my bad, Array.prototype.sort() doesn't preserve order of elements with same value of sorting criteria. I'll fix it soon (today)

2018-02-13 10:49 UTC, dkonopka commented
Left padding of every element in `.ck-list` shouldn't be the same like in heading?

![paddinglist](https://user-images.githubusercontent.com/10219857/36146001-6547e42a-10b3-11e8-9f15-79a78241168e.png)

I see some CSS overrides for the heading:
![headingpadding](https://user-images.githubusercontent.com/10219857/36146105-ce44dfa0-10b3-11e8-8cec-95699d02c07d.png)

![screen shot 2018-02-13 at 11 46 03](https://user-images.githubusercontent.com/10219857/36146040-8957c8bc-10b3-11e8-863d-7df2b325374e.png)

cc @oleq

2018-02-13 11:59 UTC, oleq commented
You're right @dkonopka. We should see this fixed.

2018-02-14 16:57 UTC, jodator commented
I've fixed another issue in Umberto (the list view in dropdown had margin and padding set): https://github.com/ckeditor/ckeditor5/issues/494#issuecomment-365671757.

Besides that dropdown looks OK.

2018-02-14 17:01 UTC, jodator commented
@oleq & @Reinmar I've updated the docs as best I could do :) The dropdown looks OK in docs now.

2018-02-15 12:12 UTC, merged